[build]
    base = "/"
    publish = "public"
    command = "npm run build"
    environment = { NODE_VERSION = "20.11.0" }

[functions]
    node_bundler = "esbuild"
    external_node_modules = ["sharp"]
    included_files = ["node_modules/sharp/**/*", "node_modules/@img/**/*"]
